### PR TITLE
Added Socialify cover to README

### PR DESCRIPTION
**Pull request by Apolo151**

### CODE REVIEW

**Comment by tusharnankani** [comment]
Hi @Apolo151
Thank you for your PR.  
Can you save it in Dark mode?

**Comment by Apolo151** [comment]
Sure, just changed it to dark mode @tusharnankani

**Comment by Apolo151** [comment]
@tusharnankani 
is there something else to change?

**Comment by tusharnankani** [comment]
Hi @Apolo151 
Apologies for the late reply, was stuck in some commitments. 

What you have done is added a static image, so whenever stars/forks etc update, they won't be updated in the poster for obvious reasons.

What you can do instead is copy the direct image URL.
image

Here's the link. 

```
![whatsapp-chat-data-analysis](https://socialify.git.ci/tusharnankani/whatsapp-chat-data-analysis/image?description=1&forks=1&issues=1&language=1&owner=1&pattern=Brick%20Wall&pulls=1&stargazers=1&theme=Dark)
```

Feel free to create a clean PR, closing this for now. 
Thank you.

**Pull request closed without merging**
